let obj = {
    data : function(){
        return {
            email : "",
            password : "",
        }
    },
    template : "         <div id='login_section'>            <div class='std_header_1'>                <p>LOGIN</p>            </div>            <div class='container'>                <div class='row'>                    <div class='f-1'>                        <div id='social_login_box'>                            <p>Login with social</p>                            <div id='gmail_login'>                                <p><span class='fab fa-google-square'></span> Login with Gmail</p>                            </div>                            <div id='facebook_login'>                                <p><span class='fab fa-facebook-square'></span> Login with facebook</p>                            </div>                            <div id='twitter_login'>                                <p><span class='fab fa-twitter-square'></span> Login with twitter</p>                            </div>                        </div>                    </div>                    <div class='f-1'>                        <form>                            <div id='login_manual_form'>                                <input type='email'>                                <input type='password'>                            </div>                            <div class='submit_container'>                                <button>Login</button>                            </div>                        </form>                    </div>                </div>                <div id='util_access_links'>                    <p>Don't have an account? <a class='sign_up_util_link' href='#'>Sign Up Now!</a></p>                    <p>Forgot your password? <span>Recover it here.</span></p>                </div>            </div>        </div>         "
}
export default obj;