let obj = {
    data : function(){
        return {
            signupemail : "",
            signuppassword : "",
            confirmpassword : ""
        }
    },
    template : "         <div id='signup_section'>            <div class='std_header_1'>                <p>SIGN UP</p>            </div>            <div class='container'>                <div class='row'>                    <div class='f-1'>                        <div id='social_login_box'>                            <p>Sign Up with social</p>                            <div id='gmail_login'>                                <p><span class='fab fa-google-square'></span> Sign Up with Gmail</p>                            </div>                            <div id='facebook_login'>                                <p><span class='fab fa-facebook-square'></span> Sign Up with facebook</p>                            </div>                            <div id='twitter_login'>                                <p><span class='fab fa-twitter-square'></span> Sign Up with twitter</p>                            </div>                        </div>                    </div>                    <div class='f-1'>                        <form id='signup-form'>                            <div id='signup_manual_form'>                                <input v-model='signupemail' type='email' placeholder='Email :'>                                <input v-model='signuppassword' type='password' placeholder='Set Password :'>                                <input v-model='confirmpassword' type='password' placeholder='Confirm Password :'>                            </div>                            <div class='submit_container'>                                <button>Sign Up</button>                            </div>                        </form>                    </div>                </div>                <div id='util_access_links'>                    <p>Already have an account? <a class='login_util_link' href='#'>Login Here!</a></p>                    <p>Forgot your password? <span>Recover it here.</span></p>                </div>            </div>        </div>         "
}
export default obj;